### ISSUE TITLE
Couldn't find 'java'. Please set JAVA_HOME

### ISSUE THREAD

**Issue by nu8** [borkdude/deps.clj#24]
I followed the Windows instruction exactly from here:

<https://github.com/borkdude/deps.clj#quickstart>

Result:

~~~
Exception in thread "main" java.lang.Exception: Couldn't find 'java'. Please
set JAVA_HOME.
   at borkdude.deps$_main.invokeStatic(deps.clj:306)
   at borkdude.deps$_main.doInvoke(deps.clj:265)
   at clojure.lang.RestFn.invoke(RestFn.java:397)
   at clojure.lang.AFn.applyToHelper(AFn.java:152)
   at clojure.lang.RestFn.applyTo(RestFn.java:132)
   at borkdude.deps.main(Unknown Source)
~~~

**Comment by borkdude** [comment]
Do you have java installed?

**Comment by nu8** [comment]
I followed the instruction exactly. I do not see an instruction to install Java

**Comment by nu8** [comment]
Correction, seems it is listed here:

https://github.com/borkdude/deps.clj#binary
